name: Build and Publish

on: 
  workflow_call:
    inputs:
      mumble_version:
        required: true
        type: string
      docker_version:
        required: true
        type: string
      platforms:
        required: true
        type: string
      publish:
        required: true
        type: boolean
      update_latest:
        required: true
        type: boolean
    secrets:
        docker_user:
          required: true
        docker_token:
          required: true

env:
  TAGS: "none"
  VERSION:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Checkout private tools
              uses: actions/checkout@v4
              with:
                repository: mumble-voip/mumble
                sparse-checkout: |
                  scripts
            - run: echo "VERSION=$( python3 "./scripts/mumble-version.py" )" >> $GITHUB_ENV
            - run: echo $VERSION
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Build
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.docker_user }}
                password: ${{ secrets.docker_token }}
            - name: Configure target tags (with latest)
              if: ${{ inputs.update_latest }}
              run: echo "TAGS=richy1989/mumble-server:latest, richy1989/mumble-server:${{ inputs.mumble_version }}, richy1989/mumble-server:${{ inputs.mumble_version }}-${{ inputs.docker_version }}" >> $GITHUB_ENV
            - name: Configure target tags (without latest)
              if: ${{ ! inputs.update_latest }}
              run: echo "TAGS=richy1989/mumble-server:${{ inputs.mumble_version }}, richy1989/mumble-server:${{ inputs.mumble_version }}-${{ inputs.docker_version }}" >> $GITHUB_ENV 
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                platforms: ${{ inputs.platforms }}
                push: ${{ inputs.publish }}
                build-args: |
                    UID=99
                    GID=100
                    MUMBLE_VERSION=${{ inputs.mumble_version }}
                tags: ${{ env.TAGS }}
              env:
                MUMBLE_VERSION: ${{ inputs.mumble_version }}
