name: Build and Publish

on:
  push:
  schedule:
    - cron: "0 16 * * 6"
env:
  mumble_version: "v1.5.634"
  docker_version: '0'
  platforms: "linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8"
  publish: false
  update_latest: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Build
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_KEY }}
            - name: Configure target tags (with latest)
              if: ${{ env.update_latest }}
              run: echo "TAGS=richy1989/mumble-server:latest, richy1989/mumble-server:${{ env.mumble_version }}, richy1989/mumble-server:${{ env.mumble_version }}-${{ env.docker_version }}" >> $GITHUB_ENV
            - name: Configure target tags (without latest)
              if: ${{ ! env.update_latest }}
              run: echo "TAGS=richy1989/mumble-server:${{ env.mumble_version }}, richy1989/mumble-server:${{ env.mumble_version }}-${{ env.docker_version }}" >> $GITHUB_ENV 
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                platforms: ${{ env.platforms }}
                push: ${{ env.publish }}
                build-args: |
                    UID=99
                    GID=100
                    MUMBLE_VERSION=${{ env.mumble_version }}
                tags: ${{ env.TAGS }}
              env:
                MUMBLE_VERSION: ${{ env.mumble_version }}
