name: CI

#on: [ push, pull_request ]
on:
    push:
    schedule:
      - cron: "0 16 * * 6"
        
# Note: As of now the strategy property is not supported when using reusable workflows, so we can't use a build
# matrix to create the different build cases (see https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations)
jobs:
    build_1_5_634:
        uses: ./.github/workflows/build_and_publish.yml
        secrets: 
            docker_user: ${{ secrets.DOCKERHUB_USER }}
            docker_token: ${{ secrets.DOCKERHUB_KEY }}
        with:
            mumble_version: "v1.5.634"
            docker_version: '0'
            publish: true
            update_latest: false
            platforms: "linux/amd64" #"linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8"

    build_latest:
        uses: ./.github/workflows/build_and_publish.yml
        secrets: 
            docker_user: ${{ secrets.DOCKERHUB_USER }}
            docker_token: ${{ secrets.DOCKERHUB_KEY }}
        with:
            mumble_version: "latest"
            docker_version: '0'
            publish: true
            update_latest: true
            platforms: "linux/amd64" #"linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8"
